config/routes.rb
Rails.application.routes.draw do

  # Application root 
  root to: 'pages#index'
  
  get '/organizations/:id/manage_members', to: 'organizations#manage_members'
  get '/organizations/:id/edit_positions', to: 'organizations#edit_positions'

  # Devise Routes
  devise_for :users,
             controllers: {
               registrations: 'nms_devise/registrations',
               sessions: 'nms_devise/sessions'}

  resources :users do 
    get 'dashboard', to: 'users#dashboard'
    get 'nms_config', to: 'users#nms_config_options'
  end

  
  resources :organizations do
    post '/organizations/:organization_id/memberships/:id' => 'memberships#leadership_status'
    post 'join'
    post 'moderate_membership'
    resources :memberships do
      patch 'add_position'
    end
    resources :positions
  end

  resources :sections do
    post 'toggle_visibility'
  end
  
  resources :articles

  resources :medias
  resources :photos

end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :headline, :bodytext, presence: true

  belongs_to :user
  belongs_to :organization
  has_many :medias

  def photos
  	medias.where(media_type: 1, article_id: id).sample
  end

end

app/models/media.rb
class Media < ActiveRecord::Base

  belongs_to :user
  belongs_to :organization

  before_destroy :remove_media

  def self.create_using_upload_type(params, user)
    media = nil

    if params.has_key? :photo
      photo = Photo.new(Media.photo_params(params))
      
      if photo.save
        media = Media.new(
          media_type: MediaTypes.find_by_type_name("Photo").id,
          media_id: photo.id,
          user_id: user.id
        )
        media.save
      end

    elsif params.has_key? :xml

    end

    return media
  end

  def remove_media
    if MediaTypes.find(media_type).type_name == "Photo" 
      photo = Photo.find_by_id(media_id)
      if photo
        photo.destroy
      end
    end
  end

  private
    def self.photo_params(params)
      params.require(:photo).permit(:image)
    end

end

app/models/media_types.rb
class MediaTypes < ActiveRecord::Base

  validates :type_name, uniqueness: true

end

app/models/membership.rb
class Membership < ActiveRecord::Base

  belongs_to :user
  belongs_to :organization
  belongs_to :position

  validates :user_id, :organization_id, presence: true
  validates :user_id, uniqueness: { scope: :organization_id }

  # 0 is membership pending, 1 is membership accepted, 2 is membership denied
  validates :approval_status, presence: true

end

app/models/nms_config.rb
class NmsConfig < ActiveRecord::Base

  validates :key, presence: true
  validates :key, uniqueness: true

end

app/models/organization.rb
class Organization < ActiveRecord::Base

  has_many :memberships, dependent: :destroy
  has_many :positions, dependent: :destroy
  has_many :articles
  has_many :medias

  validates :title, presence: true

  def leaders
    memberships.where(is_leader: true)
  end

  def self.sections_for_select(user)
    organizations = Array.new

    user.memberships.each do |mem| 
      organizations << mem.organization
    end

    if organizations.length > 1
      organizations = organizations.sort { |a,b| a.title.downcase <=> b.title.downcase }
      organizations = organizations.collect! {|org| [org.title, org.id ] }
    elsif organizations.length == 1
      organizations = [[organizations[0].title, organizations[0].id]]
    end
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :image, ImageUploader

  after_destroy :remove_media_record

  def remove_media_record
    media_record = Media.find_by_media_id(id) 
    if media_record
      media_record.destroy
    end
  end

end 

app/models/position.rb
class Position < ActiveRecord::Base

  belongs_to :oganization
  has_many :memberships

end

app/models/section.rb
class Section < ActiveRecord::Base

  validates :title, presence: true

  def self.active_sections
    Section.where(is_active: true)
  end

  def self.sections_for_select
    sections = Section.all
    if sections.length > 1
      sections = sections.sort { |a,b| a.title.downcase <=> b.title.downcase }
      sections = sections.collect! {|s| [s.title, s.id ] }
    elsif sections.length == 1
      sections = [[sections[0].title, sections[0].id]]
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships, dependent: :destroy
  has_many :articles
  has_many :medias

  validates :fname, :lname, :RIN, presence: true


  def name
    # Return the user's full name
    (fname || " ") + " " + (lname || " ")
  end

  def organizations
    # Return all organizations a user is a member of
    organizations = Array.new()
    Membership.where(user_id: self.id).each do |mem|
      organizations << Organization.find(mem.organization_id)
    end
    organizations
  end

  def is_organization_leader?(organization)
    mem = memberships.find_by_organization_id(organization.id)
    if mem.is_leader == true
      return true
    end
  end

  def self.not_in_organization(organization)
    memberships = organization.memberships

    memberships = memberships.collect! { |mem| mem.user }

    results = Array.new()
    User.all.each do |user|
      if !memberships.include? user
        results << user
      end
    end

    results
  end


end

app/controllers/medias_controller.rb
class MediasController < ApplicationController

  def index
    @media = Media.all
  end

  def show
    @media = Media.find(params[:id])
    @media_type = MediaTypes.find_by_id(@media.media_type).type_name
  end

  def new
    if !params.has_key? :upload_media_type
      @upload_media_type = MediaTypes.find_by_type_name("Photo")
    else
      @upload_media_type = MediaTypes.find_by_type_name(params[:upload_media_type])
    end
  end

  def create
    @media = Media.create_using_upload_type(params, current_user)

    if @media
      if @media.save
        redirect_to media_path(@media)
      end
    else 
      redirect_to medias_path
    end
  end

  def edit

  end

  def update

  end

  def destroy
    @media = Media.find(params[:id])
    @media.destroy

    redirect_to medias_path
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # Home page - show latest articles
  def index
    @articles = Article.all.order("updated_at desc").limit(6)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def dashboard
    @user = User.find(params[:user_id])
    @memberships = Membership.where(user_id: @user.id, approval_status: 1)
    @articles = Article.where(user_id: @user.id) 
  end

  def nms_config_options
    @nms_config_basic = NmsConfig.where(requires_admin: false)
    @nms_config_admin = NmsConfig.where(requires_admin: true)
  end

  def show
  end

  def new
  end

  def created
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to user_dashboard_path(@user)
  end

  def destroy
  end

  private
    def user_params 
       params.require(:user).permit(:email, :fname, :lname, :RIN, :year)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	def page_title(content)
		content_for :page_title, content.to_s
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper

	def can_edit_article?(article)
		# Determine if current user has permissions to edit and article
		if current_user.is_admin? 
			# user is system admin
			return true
		elsif article.user_id == current_user.id
			# user is article author
			return true
		elsif organization = Organization.find_by_id(article.organization_id)
			organization.leaders.each do |leader|
				if leader.user_id == current_user.id
					# user is publishing organization's leader
					return true
				else
					return false
				end
			end
		else
			return false
		end
	end

end

app/helpers/medias_helper.rb
module MediasHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/nms_config_helper.rb
module NmsConfigHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/medias/index.html.erb
<div class="panel panel-default">

  <ol class="breadcrumb">
    <li><%= link_to "Dashboard", user_dashboard_path(current_user) %></li>
    <li class="active"> Media Index </li>
    <div class="pull-right">
      <%= link_to "Upload media", new_media_path, :class => "btn btn-default btn-xs" %>
    </div>
  </ol>

  <div class="panel-body">
    <table class="table">
      <tr>
        <th> Media Type </th>
        <th> View Media </th>
        <th> Attr. User </th>
        <th> Attr. Organization </th>
        <th> Actions </th>
      </tr>
      <% @media.each do |m| %>
        <tr>
          <td> <%= MediaTypes.find(m.media_type).type_name %> </td>
          <td> <%= link_to m.media_id %> </td>
          <td> <%= link_to m.user_id, user_path(id: m.user_id) %> </td>
          <td> <%= m.organization_id %> </td>
          <td> 
            <%= button_to "Delete", media_path(m), method: :delete, :class => "btn btn-danger btn-xs" %>
          <td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/medias/media_forms/_photo.html.erb
<h3> Photo upload </h3>
<br />
<%= form_for :photo, html: {multipart: true}, url: medias_path, method: :create do |f| %>
  <p>
    <%= f.file_field :image %>
  </p>
  <p> 
    <h4> Link to article (optional) </h4>

  </p>
  <p>
    <h4> 
  </p>
  <p>
    <%= f.submit "Upload" %>
  </p>
<% end %>

app/views/medias/new.html.erb
<div class="panel panel-default">

  <ol class="breadcrumb">
    <li><%= link_to "Dashboard", user_dashboard_path(current_user) %></li>
    <li><%= link_to "Media Index", medias_path %></li>
    <li class="active"> Upload Media </li>
  </ol>

  <div class="panel-body">
    <ul class="nav nav-tabs">
      <% all_media_types = MediaTypes.all %>
      <% all_media_types.each do |mt| %>
         <li class="<%= if mt.type_name == @upload_media_type.type_name then 'active' else '' end %>"> 
          <%= link_to mt.type_name, new_media_path(upload_media_type: mt.type_name) %>
        </li>
      <% end %>
    </ul>

    <br />

    <%= render partial: "medias/media_forms/#{@upload_media_type.type_name.downcase}" %>
  </div>
</div>

app/views/medias/show.html.erb
<%= render partial: "#{@media_type.downcase.pluralize}/display.html.erb" %>