config/routes.rb
Rails.application.routes.draw do

  # Application root 
  root to: 'pages#index'
  
  get '/organizations/:id/manage_members', to: 'organizations#manage_members'
  get '/organizations/:id/edit_positions', to: 'organizations#edit_positions'

  # Devise Routes
  devise_for :users,
             controllers: {
               registrations: 'nms_devise/registrations',
               sessions: 'nms_devise/sessions'}

  resources :users do 
    get 'dashboard', to: 'users#dashboard'
    get 'nms_config', to: 'users#nms_config_options'
  end

  
  resources :organizations do
    post '/organizations/:organization_id/memberships/:id' => 'memberships#leadership_status'
    post 'join'
    post 'moderate_membership'
    resources :memberships do
      patch 'add_position'
    end
    resources :positions
  end

  resources :sections do
    post 'toggle_visibility'
  end
  
  resources :articles

  resources :medias
  resources :photos

end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :headline, :bodytext, presence: true

  belongs_to :user
  belongs_to :organization
  has_many :medias

  def photos
  	medias.where(media_type: 1, article_id: id).sample
  end

end

app/models/media.rb
class Media < ActiveRecord::Base

  belongs_to :user
  belongs_to :organization

  before_destroy :remove_media

  def self.create_using_upload_type(params, user)
    media = nil

    if params.has_key? :photo
      photo = Photo.new(Media.photo_params(params))
      
      if photo.save
        media = Media.new(
          media_type: MediaTypes.find_by_type_name("Photo").id,
          media_id: photo.id,
          user_id: user.id
        )
        media.save
      end

    elsif params.has_key? :xml

    end

    return media
  end

  def remove_media
    if MediaTypes.find(media_type).type_name == "Photo" 
      photo = Photo.find_by_id(media_id)
      if photo
        photo.destroy
      end
    end
  end

  private
    def self.photo_params(params)
      params.require(:photo).permit(:image)
    end

end

app/models/media_types.rb
class MediaTypes < ActiveRecord::Base

  validates :type_name, uniqueness: true

end

app/models/membership.rb
class Membership < ActiveRecord::Base

  belongs_to :user
  belongs_to :organization
  belongs_to :position

  validates :user_id, :organization_id, presence: true
  validates :user_id, uniqueness: { scope: :organization_id }

  # 0 is membership pending, 1 is membership accepted, 2 is membership denied
  validates :approval_status, presence: true

end

app/models/nms_config.rb
class NmsConfig < ActiveRecord::Base

  validates :key, presence: true
  validates :key, uniqueness: true

end

app/models/organization.rb
class Organization < ActiveRecord::Base

  has_many :memberships, dependent: :destroy
  has_many :positions, dependent: :destroy
  has_many :articles
  has_many :medias

  validates :title, presence: true

  def leaders
    memberships.where(is_leader: true)
  end

  def self.sections_for_select(user)
    organizations = Array.new

    user.memberships.each do |mem| 
      organizations << mem.organization
    end

    if organizations.length > 1
      organizations = organizations.sort { |a,b| a.title.downcase <=> b.title.downcase }
      organizations = organizations.collect! {|org| [org.title, org.id ] }
    elsif organizations.length == 1
      organizations = [[organizations[0].title, organizations[0].id]]
    end
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :image, ImageUploader

  after_destroy :remove_media_record

  def remove_media_record
    media_record = Media.find_by_media_id(id) 
    if media_record
      media_record.destroy
    end
  end

end 

app/models/position.rb
class Position < ActiveRecord::Base

  belongs_to :oganization
  has_many :memberships

end

app/models/section.rb
class Section < ActiveRecord::Base

  validates :title, presence: true

  def self.active_sections
    Section.where(is_active: true)
  end

  def self.sections_for_select
    sections = Section.all
    if sections.length > 1
      sections = sections.sort { |a,b| a.title.downcase <=> b.title.downcase }
      sections = sections.collect! {|s| [s.title, s.id ] }
    elsif sections.length == 1
      sections = [[sections[0].title, sections[0].id]]
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships, dependent: :destroy
  has_many :articles
  has_many :medias

  validates :fname, :lname, :RIN, presence: true


  def name
    # Return the user's full name
    (fname || " ") + " " + (lname || " ")
  end

  def organizations
    # Return all organizations a user is a member of
    organizations = Array.new()
    Membership.where(user_id: self.id).each do |mem|
      organizations << Organization.find(mem.organization_id)
    end
    organizations
  end

  def is_organization_leader?(organization)
    mem = memberships.find_by_organization_id(organization.id)
    if mem.is_leader == true
      return true
    end
  end

  def self.not_in_organization(organization)
    memberships = organization.memberships

    memberships = memberships.collect! { |mem| mem.user }

    results = Array.new()
    User.all.each do |user|
      if !memberships.include? user
        results << user
      end
    end

    results
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # Home page - show latest articles
  def index
    @articles = Article.all.order("updated_at desc").limit(6)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def dashboard
    @user = User.find(params[:user_id])
    @memberships = Membership.where(user_id: @user.id, approval_status: 1)
    @articles = Article.where(user_id: @user.id) 
  end

  def nms_config_options
    @nms_config_basic = NmsConfig.where(requires_admin: false)
    @nms_config_admin = NmsConfig.where(requires_admin: true)
  end

  def show
  end

  def new
  end

  def created
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to user_dashboard_path(@user)
  end

  def destroy
  end

  private
    def user_params 
       params.require(:user).permit(:email, :fname, :lname, :RIN, :year)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	def page_title(content)
		content_for :page_title, content.to_s
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper

	def can_edit_article?(article)
		# Determine if current user has permissions to edit and article
		if current_user.is_admin? 
			# user is system admin
			return true
		elsif article.user_id == current_user.id
			# user is article author
			return true
		elsif organization = Organization.find_by_id(article.organization_id)
			organization.leaders.each do |leader|
				if leader.user_id == current_user.id
					# user is publishing organization's leader
					return true
				else
					return false
				end
			end
		else
			return false
		end
	end

end

app/helpers/medias_helper.rb
module MediasHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/nms_config_helper.rb
module NmsConfigHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_account_details.html.erb
<% if @user.is_admin %> 
  <h4> <b>SYSTEM ADMIN</b> </h4>
<% end %>
<%= link_to "Edit User", edit_user_path(@user), :class => "btn btn-default pull-right" %>
<b> Name: </b> <%= @user.name %> <br/>
<b> RIN: </b> <%= @user.RIN %> <br />
<b> email: </b> <%= @user.email %> <br />
<b> year: </b> <%= @user.year %> <br />
<b> account last edit: </b> <%= @user.updated_at %> <br />
<b> member since: </b> <%= @user.created_at %> <br />
<b> sign in count: </b> <%= @user.sign_in_count %> <br />
<b> last sign in: </b> <%= @user.last_sign_in_at %> <br />
<b> last ip: </b> <%= @user.last_sign_in_ip %> <br />

app/views/users/_dashboard_articles.html.erb
<!-- Articles -->
<h3> Articles </h3>
<hr />
  <% if @articles.size > 0 %>
    <% @articles.each do |article| %>
      <%= link_to article.headline, article_path(article) %>
      <br />
    <% end %>
  <% else %>
    You haven't published any articles yet
  <% end %>

app/views/users/_dashboard_controls.html.erb
<div class="row"> 
  <div class="col-md-10 col-md-offset-1 breadcrumb">
    <h3>
      <% if @user.is_admin %>
        <%= icon("bolt") %>
      <% end %>
      <%= @user.name %>
      <%= link_to "New Article", new_article_path, :class => "btn" %>
      <%= link_to "Join Organizations", organizations_path, :class => "btn" %>
      <%= link_to "Settings", user_nms_config_path, :class => "btn" %>

      <div class="pull-right">
        <% if current_user.is_admin? %>
          Admin Controls
          <%= link_to "Article Sections", sections_path, :class => "btn" %>
          <%= link_to "Article Index", articles_path, :class => "btn" %>
          <%= link_to "Media Index", medias_path, :class => "btn" %>
          <%= link_to "User Index", users_path, :class => "btn"%>
        <% end %>
      </div>
    </h3>
  </div>
</div>

app/views/users/_dashboard_organizations.html.erb
<!-- Organizations -->
<h3> Your Organizations </h3>
<hr />
  <% if @memberships.size > 0 %>
    <% @memberships.each do |mem| %>
     <%= link_to mem.organization.title, organization_path(mem.organization) %> <br />
    <% end %>
  <% else %>
    You're not a member of any organizations
  <% end %>

app/views/users/_nms_config.html.erb
<div class="row">
  <div class="col-md-6">
    <h3> Settings </h3>
    <%= render partial: "nms_config/options.html.erb" %>
  </div>
</div>

app/views/users/dashboard.html.erb
	<%= render partial: "dashboard_controls" %>

	<hr />

	<div class="row">
		<div class="col-md-4 col-md-offset-2" style="padding-right:20px; border-right: 1px solid #eee;">
			<%= render partial: "dashboard_organizations" %>
		</div>
		<div class="col-md-4">
			<%= render partial: "dashboard_articles" %>
		</div>
	</div>

app/views/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3> <%= "Editing Account - #{@user.name}" %> </h3>
  </div>
  <div class="panel-body">
    <%= form_for @user do |f| %>

      <div class="input-group">
        <span class="input-group-addon">Email</span>
        <%= f.text_field :email,  :class=>"form-control" %>
      </div><br/>

      <div class="input-group">
        <span class="input-group-addon">First</span>
        <%= f.text_field :fname, :class=>"form-control" %>
      </div><br/>

      <div class="input-group">
        <span class="input-group-addon">Last</span>
        <%= f.text_field :lname, :class=>"form-control" %>
      </div><br/>

      <div class="input-group">
        <span class="input-group-addon">RIN</span>
        <%= f.text_field :RIN, :class=>"form-control" %>
      </div><br/>
      
      <div class="input-group">
        <span class="input-group-addon">Year</span>
        <%= f.text_field :year, :class=>"form-control" %>
      </div>

      <br />
      <%= f.submit :class => "btn btn-default" %> <%= link_to "Deactivate Account", "#", :class => "btn btn-warning pull-right" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="panel panel-default">

  <ol class="breadcrumb">
    <li><%= link_to "Dashboard", user_dashboard_path(current_user) %></li>
    <li class="active"> Users Index </li>
  </ol>

  <div class="panel-body">
    <table class="table">
      <tr>
        <th> Name </th>
        <th> Organizations </th>
        <th> Actions </th>
      </tr>

      <% @users.each do |user| %>
        <tr> 
          <td> 
            <%= user.name %> 
          </td>
          <td>
            <% user.organizations.each do |org| %>
              <%= org.title %>
            <% end %>
          </td>
          <td>
            <%= link_to "Edit", "users/edit", :class => "btn btn-xs" %>
            <%= link_to "Delete", "", :class =>"btn btn-xs" %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/nms_config_options.html.erb
<%= render partial: "nms_config/options.html.erb" %>