config/routes.rb
Rails.application.routes.draw do

  # Application root 
  root to: 'pages#index'
  
  get '/organizations/:id/manage_members', to: 'organizations#manage_members'
  get '/organizations/:id/edit_positions', to: 'organizations#edit_positions'

  # Devise Routes
  devise_for :users,
             controllers: {
               registrations: 'nms_devise/registrations',
               sessions: 'nms_devise/sessions'}

  resources :users do 
    get 'dashboard', to: 'users#dashboard'
    get 'nms_config', to: 'users#nms_config_options'
  end

  
  resources :organizations do
    post '/organizations/:organization_id/memberships/:id' => 'memberships#leadership_status'
    post 'join'
    post 'moderate_membership'
    resources :memberships do
      patch 'add_position'
    end
    resources :positions
  end

  resources :sections do
    post 'toggle_visibility'
  end
  
  resources :articles

  resources :medias
  resources :photos

end

app/models/organization.rb
class Organization < ActiveRecord::Base

  has_many :memberships, dependent: :destroy
  has_many :positions, dependent: :destroy
  has_many :articles
  has_many :medias

  validates :title, presence: true

  def leaders
    memberships.where(is_leader: true)
  end

  def self.sections_for_select(user)
    organizations = Array.new

    user.memberships.each do |mem| 
      organizations << mem.organization
    end

    if organizations.length > 1
      organizations = organizations.sort { |a,b| a.title.downcase <=> b.title.downcase }
      organizations = organizations.collect! {|org| [org.title, org.id ] }
    elsif organizations.length == 1
      organizations = [[organizations[0].title, organizations[0].id]]
    end
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @organizations = Organization.all
  end

  def show
    @organization = Organization.find(params[:id])

    membership = Membership.find_by_user_id(current_user.id)
    if membership
      @is_leader = membership.is_leader?
    end
  end

  def manage_members
    @organization = Organization.find(params[:id])
    @memberships = Membership.where(organization_id: @organization.id, approval_status: 1)
    @positions = @organization.positions
    
    @requests = Membership.where(organization_id: @organization.id, approval_status: 0)
    @rejections = Membership.where(organization_id: @organization.id, approval_status: 2)

    @users = User.not_in_organization(@organization)
    if @users.length > 1
      @users = @users.sort { |a,b| a.name.downcase <=> b.name.downcase }
      @users = @users.collect! {|u| [u.name, u.id ] }
    elsif @users.length == 1
      @users = [[@users[0].name, @users[0].id]]
    end

    if @positions.length > 1
      @positions = @positions.sort { |a,b| a.title.downcase <=> b.title.downcase }
      @positions = @positions.collect! {|p| [p.title, p.id ] }
    elsif @positions.length == 1
      @positions = [[@positions[0].title, @positions[0].id]]
    end
  end

  def join
    membership = Membership.new( user_id: current_user.id,
      organization_id: params[:organization_id],
      is_leader: false, approval_status: 0)

    membership.save 

    redirect_to organizations_path
  end

  def moderate_membership
    membership = Membership.find(params[:membership_id])
    membership.update_attributes(approval_status: params[:approval_status])

    redirect_to manage_members_path(Organization.find(params[:organization_id]))
  end

  def edit_positions
    @organization = Organization.find(params[:id])
    @positions = @organization.positions
  end

  def new
  end

  def create
    @organization = Organization.new(organization_params)
    @organization.save

    redirect_to @organization
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private 
    def organization_params 
       params.require(:organization).permit(:title)
    end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_manage_current_members.html.erb
<h4> Current Members </h4>
<table class="table">
  <tr>
    <th> Name </th>
    <th> Position </th>
    <th> Actions </th>
  </tr>
  <% @memberships.each do |mem| %>
    <% if mem.user.is_active? %>
      <tr>
        <td>
          <%= mem.user.name %> 
          <%= if mem.is_leader then icon("certificate") end %>
        </td>
        <td>
          <% if !@positions.nil? and @positions.length > 0 %>
            <%= form_for mem, url: organization_membership_add_position_path(organization_id: params[:id], membership_id: mem.id), method: :patch do |f| %>
              <%= f.select :position_id, @positions, { include_blank: true } %>
              <%= f.submit "Update", :class => "btn btn-xs btn-confirm" %>
            <% end %>
          <% end %>
        </td>
        <%= render partial: "manage_members_actions", locals: { mem: mem} %>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/organizations/_manage_inactive_members.html.erb
<h4> Inactive Members </h4>
<table class="table">
  <tr>
    <th> Name </th>
    <th> Position </th>
    <th> Actions </th>
  </tr>
  <% @memberships.each do |mem| %>
    <% if !mem.user.is_active? %>
      <tr> 
        <td> <%= mem.user.name %> </td>
        <td>
        </td>
        <%= render partial: "manage_members_actions", locals: { mem: mem} %>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/organizations/_manage_members_actions.html.erb
<td>
<%= button_to "Remove", 
          organization_membership_path(organization_id: params[:id], id: mem.id), 
          method: :delete,
          :class => "btn btn-danger btn-xs button_to" %>
<% if !mem.is_leader %>
  <%= button_to "Promote to Leader", 
            {controller: :memberships, action: 'leadership_status', organization_id: params[:id], id: mem.id },
            method: :leadership_status,
            :class => "btn btn-success btn-xs button_to" %>
  </td>
<% else %>
  <%= button_to "Demote to Member", 
            {controller: :memberships, action: 'leadership_status',organization_id: params[:id], id: mem.id },
            method: :leadership_status,
            :class => "btn btn-success btn-xs button_to" %>
<% end %>
</td>

app/views/organizations/_manage_rejections.html.erb
<h4> Membership Rejections </h4>
<table class="table">
  <tr>
    <th> Name </th>
    <th> Actions </th>
  </tr>
  <% @rejections.each do |rej| %>
    <tr>
      <td> <%= rej.user.name %> </td>
      <td> <%= button_to "Unblock and Approve", organization_moderate_membership_path(@organization, membership_id: rej.id, approval_status: 1) , :class => "btn btn-confirm btn-xs" %>
    </tr>
  <% end %>
</table>

app/views/organizations/_manage_requests.html.erb
<h4> Membership Requests </h4>
<table class="table">
  <tr>
    <th> Name </th>
    <th> Actions </th>
  </tr>
  <% @requests.each do |req| %>
    <tr> 
      <td> <%= req.user.name %> </td>
      <td> 
        <%= button_to "Accept", organization_moderate_membership_path(@organization, membership_id: req.id, approval_status: 1), :class => "btn btn-success btn-xs" %>
        <%= button_to "Reject", organization_moderate_membership_path(@organization, membership_id: req.id, approval_status: 2) , :class => "btn btn-danger btn-xs" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/organizations/edit_positions.html.erb
<div class="panel panel-default">
    <ol class="breadcrumb">
      <li><%= link_to "Dashboard", user_dashboard_path(current_user) %></li>
      <li><%= link_to @organization.title, organization_path(@organization) %></li>
      <li class="active">Edit Positions</li>
    </ol>

  <div class="panel-body">
    <h3> Current positions </h3>
    <br />
    <% if !@positions.nil? %>
      <% @positions.each do |pos| %>
        <b><%= pos.title %></b>
        <% if pos.memberships.length > 0 %>
          <% pos.memberships.each do |mem| %>
            <%= "- #{mem.user.name}" %>
          <% end%>
        <% else %>
          - <%= link_to "Assign to a member", manage_members_path(@organization) %>
        <% end %>
        <br />
      <% end %>
    <% end %>

    <hr />

    <h3> Add a new position </h3><br/>
    <%= form_for :position, url: organization_positions_path(organization_id: params[:id]), method: :post do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.submit :class => "btn btn-xs btn-confirm" %>
    <% end %>
    <hr />

  </div>

</div>

app/views/organizations/index.html.erb
<div class="panel panel-default">

  <ol class="breadcrumb">
    <li><%= link_to "Dashboard", user_dashboard_path(current_user) %></li>
    <li class="active"> Organizations </li>
    <% if current_user.is_admin? %>     
      <%= link_to "New Organization", new_organization_path, :class => "btn btn-default btn-xs pull-right" %>
    <% end %>
  </ol>

  <div class="panel-body">

    <table class="table">
      <tr>
        <th> Organization Name </th>
        <th> </th>
      </tr>
      <% @organizations.each do |org| %>
        <tr>
          <td> <%= link_to org.title, org %> </td>
          <% 
            mem = nil
            org.memberships.each do |membership| 
              if membership.user_id == current_user.id 
                mem = membership
              end
            end
          %>
          <% if mem.nil? %>
            <td> <%= button_to "Join", organization_join_path(org), :class => "btn btn-xs btn-confirm" %></td>
          <% elsif mem.approval_status == 1 %>
              <td> You're already a member </td>
          <% elsif mem.approval_status == 0 %>
            <td> Your request has been sent. </td>
          <% elsif mem.approval_status == 2 %>
            <td> Your request has been denied. </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/organizations/manage_members.html.erb
<div class="panel panel-default">
    <ol class="breadcrumb">
      <li><%= link_to "Dashboard", user_dashboard_path(current_user) %></li>
      <li><%= link_to @organization.title, organization_path(@organization) %></li>
      <li class="active">Manage Members</li>
    </ol>

  <div class="panel-body">

    <% if @users.length > 0 %>
    <h4> Add New Member: </h4>
    <br />
      <% if @users %>
        <%= form_for :membership, url: organization_memberships_path(organization_id: params[:id]), method: :post do |f| %>
          <%= f.select :user_id, @users, { include_blank: true } %>
          <%= f.label "Leader?" %>
          <%= f.check_box :is_leader %>
          <br />
          <%= f.submit "Add ", :class => "btn btn-xs btn-confirm" %>
        <% end %>
      <% end %> 
      <hr />
    <% end %>

    <% if @requests.length > 0%>
      <div class="well">
        <%= render partial: "manage_requests" %>
      </div>
    <% end %>

    <% if @memberships %>
      <%= render partial: "manage_current_members" %>
      <%= render partial: "manage_inactive_members" %>
    <% end %>

    <% if @rejections.length > 0 %>
      <%= render partial: "manage_rejections" %>
    <% end %>

  </div>
</div>

app/views/organizations/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3> New Organization </h3>
  </div>
  <div class="panel-body">
    <br />
    <div class="col-md-6">
      <%= form_for :organization, url: organizations_path do |f| %>

        <div class="input-group input-group-sm">
          <span class="input-group-addon">Organization Name</span>
          <%= f.text_field :title, :class=>"form-control", maxlength: 40 %>
        </div><br/>

        <%= f.submit :class => "btn btn-default btn-sm" %>

      <% end %>
    </div>

  </div>
</div>

app/views/organizations/show.html.erb
<div class="panel panel-default">
  <ol class="breadcrumb">
    <li><%= link_to "Dashboard", user_dashboard_path(current_user) %></li>
    <li class="active"><%= @organization.title %></li>
    <% if current_user.is_admin? || @is_leader %> 
      <div class="pull-right">
        <%= link_to "Edit Positions", edit_positions_path(@organization), :class => "btn btn-default btn-xs" %>
        <%= link_to "Manage Members", manage_members_path(@organization), :class => "btn btn-default btn-xs" %>
      </div>
    <% end %>
  </ol>

  <div class="panel-body">
    <h4><b>Members</b></h4>
    <br />
    <table class="table">
      <tr>
        <th> Name </th>
        <th> Position </th>
      </tr>
      <% @organization.memberships.each do |mem| %>
        <% if mem.approval_status == 1 %>
          <tr>
            <td> 
              <%= link_to mem.user.name, user_path(mem.user) %>
              <%= if mem.is_leader then icon("certificate") end %>
            </td>
            <td>
              <% if mem.position %>
                <%= mem.position.title %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
</div>