config/routes.rb
Rails.application.routes.draw do

  # Application root 
  root to: 'pages#index'
  
  get '/organizations/:id/manage_members', to: 'organizations#manage_members'
  get '/organizations/:id/edit_positions', to: 'organizations#edit_positions'

  # Devise Routes
  devise_for :users,
             controllers: {
               registrations: 'nms_devise/registrations',
               sessions: 'nms_devise/sessions'}

  resources :users do 
    get 'dashboard', to: 'users#dashboard'
    get 'nms_config', to: 'users#nms_config_options'
  end

  
  resources :organizations do
    post '/organizations/:organization_id/memberships/:id' => 'memberships#leadership_status'
    post 'join'
    post 'moderate_membership'
    resources :memberships do
      patch 'add_position'
    end
    resources :positions
  end

  resources :sections do
    post 'toggle_visibility'
  end
  
  resources :articles

  resources :medias
  resources :photos

end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :headline, :bodytext, presence: true

  belongs_to :user
  belongs_to :organization
  has_many :medias

  def photos
  	medias.where(media_type: 1, article_id: id).sample
  end

end

app/models/media.rb
class Media < ActiveRecord::Base

  belongs_to :user
  belongs_to :organization

  before_destroy :remove_media

  def self.create_using_upload_type(params, user)
    media = nil

    if params.has_key? :photo
      photo = Photo.new(Media.photo_params(params))
      
      if photo.save
        media = Media.new(
          media_type: MediaTypes.find_by_type_name("Photo").id,
          media_id: photo.id,
          user_id: user.id
        )
        media.save
      end

    elsif params.has_key? :xml

    end

    return media
  end

  def remove_media
    if MediaTypes.find(media_type).type_name == "Photo" 
      photo = Photo.find_by_id(media_id)
      if photo
        photo.destroy
      end
    end
  end

  private
    def self.photo_params(params)
      params.require(:photo).permit(:image)
    end

end

app/models/media_types.rb
class MediaTypes < ActiveRecord::Base

  validates :type_name, uniqueness: true

end

app/models/membership.rb
class Membership < ActiveRecord::Base

  belongs_to :user
  belongs_to :organization
  belongs_to :position

  validates :user_id, :organization_id, presence: true
  validates :user_id, uniqueness: { scope: :organization_id }

  # 0 is membership pending, 1 is membership accepted, 2 is membership denied
  validates :approval_status, presence: true

end

app/models/nms_config.rb
class NmsConfig < ActiveRecord::Base

  validates :key, presence: true
  validates :key, uniqueness: true

end

app/models/organization.rb
class Organization < ActiveRecord::Base

  has_many :memberships, dependent: :destroy
  has_many :positions, dependent: :destroy
  has_many :articles
  has_many :medias

  validates :title, presence: true

  def leaders
    memberships.where(is_leader: true)
  end

  def self.sections_for_select(user)
    organizations = Array.new

    user.memberships.each do |mem| 
      organizations << mem.organization
    end

    if organizations.length > 1
      organizations = organizations.sort { |a,b| a.title.downcase <=> b.title.downcase }
      organizations = organizations.collect! {|org| [org.title, org.id ] }
    elsif organizations.length == 1
      organizations = [[organizations[0].title, organizations[0].id]]
    end
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :image, ImageUploader

  after_destroy :remove_media_record

  def remove_media_record
    media_record = Media.find_by_media_id(id) 
    if media_record
      media_record.destroy
    end
  end

end 

app/models/position.rb
class Position < ActiveRecord::Base

  belongs_to :oganization
  has_many :memberships

end

app/models/section.rb
class Section < ActiveRecord::Base

  validates :title, presence: true

  def self.active_sections
    Section.where(is_active: true)
  end

  def self.sections_for_select
    sections = Section.all
    if sections.length > 1
      sections = sections.sort { |a,b| a.title.downcase <=> b.title.downcase }
      sections = sections.collect! {|s| [s.title, s.id ] }
    elsif sections.length == 1
      sections = [[sections[0].title, sections[0].id]]
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships, dependent: :destroy
  has_many :articles
  has_many :medias

  validates :fname, :lname, :RIN, presence: true


  def name
    # Return the user's full name
    (fname || " ") + " " + (lname || " ")
  end

  def organizations
    # Return all organizations a user is a member of
    organizations = Array.new()
    Membership.where(user_id: self.id).each do |mem|
      organizations << Organization.find(mem.organization_id)
    end
    organizations
  end

  def is_organization_leader?(organization)
    mem = memberships.find_by_organization_id(organization.id)
    if mem.is_leader == true
      return true
    end
  end

  def self.not_in_organization(organization)
    memberships = organization.memberships

    memberships = memberships.collect! { |mem| mem.user }

    results = Array.new()
    User.all.each do |user|
      if !memberships.include? user
        results << user
      end
    end

    results
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def page_title(content)
		content_for :page_title, content.to_s
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper

	def can_edit_article?(article)
		# Determine if current user has permissions to edit and article
		if current_user.is_admin? 
			# user is system admin
			return true
		elsif article.user_id == current_user.id
			# user is article author
			return true
		elsif organization = Organization.find_by_id(article.organization_id)
			organization.leaders.each do |leader|
				if leader.user_id == current_user.id
					# user is publishing organization's leader
					return true
				else
					return false
				end
			end
		else
			return false
		end
	end

end

app/helpers/medias_helper.rb
module MediasHelper
end

app/helpers/nms_config_helper.rb
module NmsConfigHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <%= link_to "Home", "/" %> |
  <%= link_to "Contact", "/" %> | 
  <%= link_to "Advertise", "/" %> |
  <% if user_signed_in? %>
    <%= link_to "Dashboard" , user_dashboard_path(current_user) %> | 
    <%= link_to "Profile", user_path(current_user) %> | 
    <%= link_to "Log out", destroy_user_session_path %> 
  <% else %>
    <%= link_to "Log in", new_user_session_path %> 
  <% end %>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
  <div class="header-row-1 row">
    <div class="col-md-6 col-xs-12">
      <div class="center">
        <%= link_to root_url, "data-no-turbolink" => true do %>
          <%= image_tag "site/mast.svg", alt: "poly mast", class: "logo" %>
        <% end %>
      </div>
    </div>
    <div id="connect-buttons" class="col-md-6 col-xs-12 center kill-mobile">
      <div>
        <a href="http://twitter.com/RPIPoly"><i class="fa fa-twitter-square fa-3x"></i></a>
        <a href="http://facebook.com/thepolytechnic"><i class="fa fa-facebook-square fa-3x"></i></a>
        <a href="http://reddit.com/u/ThePolytechnic"><i class="fa fa-reddit-square fa-3x"></i></a>
        <a href="http://youtube.com/RPIPoly"><i class="fa fa-youtube-square fa-3x"></i></a>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div id="sections">
        <%= render partial: "layouts/news_sections" %>
      </div>
    </div>
  </div>
<!-- add search! -->
</header>

app/views/layouts/_header_small.html.erb
<header id="header">
  <div class="header-row-1-sm row">
    <div class="col-md-6 col-xs-12">
      <div class="center">
        <%= link_to root_url, "data-no-turbolink" => true do %>
          <%= image_tag "site/mast.svg", alt: "poly mast", class: "logo-sm" %>
        <% end %>
      </div>
    </div>
    <div id="connect-buttons" class="col-md-6 col-xs-12 center kill-mobile">
      <div>
        <a href="http://twitter.com/RPIPoly"><i class="fa fa-twitter-square fa-3x"></i></a>
        <a href="http://facebook.com/thepolytechnic"><i class="fa fa-facebook-square fa-3x"></i></a>
        <a href="http://reddit.com/u/ThePolytechnic"><i class="fa fa-reddit-square fa-3x"></i></a>
        <a href="http://youtube.com/RPIPoly"><i class="fa fa-youtube-square fa-3x"></i></a>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div id="sections-sm">
        <%= render partial: "layouts/news_sections" %>
      </div>
    </div>
  </div>
<!-- add search! -->
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_news_sections.html.erb
<ul>
	<% Section.active_sections.each do |section| %>
	<li><%= link_to section.title, section_path(section) %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>
    <% if content_for?(:page_title) %>
    <%= yield(:page_title) %>
    <% else %>
    The Rensselaer Polytechnic | Serving the Rensselaer community since 1885
    <% end %>
  </title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application.css" %>
  <link rel="icon" type="image/png" href="assets/favicon.png">
  <%= javascript_include_tag "application.js" %>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:600,900,600italic,900italic|Droid+Serif:400,700,400italic,700italic|Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <main role="main">
    <div class="container-fluid">
      <div class="row">
        <!-- Page header -->
        <%= render partial: "layouts/header_small" %>
      </div>
      <div class="content">
        <div class="row">
          <div id="header-spacer"></div>
        </div>
        <div class="row">
          <div class="span12">
            <!-- Flash messages -->
            <%= render partial: "layouts/messages" %>
            <!-- Page content -->
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </main>
  <!-- Footer -->
  <%= render partial: "layouts/footer" %>
</body>
</html>